import { registerPlugin } from '@wordpress/plugins'
import { subscribe, select, dispatch } from '@wordpress/data'
import { store as coreStore } from '@wordpress/core-data'
import domReady from '@wordpress/dom-ready'
import { regs } from './app/rules'
import { SidebarSettings } from './components'
import { fixIt } from './app/fix'
import { isUsedByLocale, getAllInnersFromParents } from './app/helpers'

let contentPasted = false

let theRegs = []

const processedBlocksForCopyPaste = [
	'core/paragraph',
	'core/heading',
	'core/quote',
	'core/freeform',
	'core/read-more',
]

const { getBlocks, getSelectedBlockClientId } = select( 'core/block-editor' )
const { getEntityRecord } = select( 'core' )
const { updateBlockAttributes, selectBlock, resetSelection } = dispatch( 'core/block-editor' )

registerPlugin( 'consistency-custom-sidebar', {
    render: SidebarSettings,
} )

domReady( () => {

	// Fixes the typography of all blocks in the post that are part of the intended list named "processedBlocksForCopyPaste"
	const fixAll = () => {
		// Get all blocks generated by pasting (which doesn't embed innerBlocks)
		const allBlocks = getBlocks()

		// Get all innerBlocks for a later selection process that will generate correction
		const allInners = getAllInnersFromParents( allBlocks )
	
		// Fixes all parents blocks
		const updates = allBlocks.reduce( ( acc, block ) => {

			let newContent = block.attributes?.content

			Object.entries( theRegs ).forEach( ( [ _, reg ] ) => {

				if ( processedBlocksForCopyPaste.includes( block.name )
					&& undefined !== newContent
					&& isUsedByLocale( reg.name ) ) {
					newContent = newContent.replaceAll( reg.mask, reg.replace )
				}

			} )

			if ( undefined !== newContent && processedBlocksForCopyPaste.includes( block.name ) ) {
				acc[ block.clientId ] = { content: newContent }
				return acc
			}
			return acc
		}, {} )

		// Update all parents blocks
		if ( Object.keys( updates ).length && contentPasted ) {
			contentPasted = false
			updateBlockAttributes( Object.keys( updates ), updates, true )
		}

		// Select all innerBlocks to trigger their correction, then deselect all by selecting the first block
		allInners.forEach( block => { 
			block?.clientId && selectBlock( block.clientId )
		} )
		allInners && allInners[0] && resetSelection( allInners[0]?.clientId, allInners[0]?.clientId )

	}

	// Intercept clipboard paste to fix all new blocks
	document.querySelector( ' #editor ' )?.addEventListener( 'paste', e => {
		contentPasted = true
		e.preventDefault()
	} )

	// Let’s listen for state changes
	subscribe( () => {

		// Check if consistency is active for current user
		const currentUser = select( coreStore ).getCurrentUser()
		const idUser = currentUser?.id || 0
		const currentUserEntity = getEntityRecord( 'root', 'user', idUser, 'consistency_plugin_setting_state' )
		if ( ! currentUserEntity?.meta?.consistency_plugin_setting_state[0] ) return

		// Get Global settings from site entity
		const siteEntity = getEntityRecord( 'root', 'site' )
		const settings = siteEntity?.consistency_plugin_settings
		if ( undefined === settings ) return
	
		theRegs = regs.filter( reg => true === settings?.find( s => s.slug === reg.name )?.value )

		// Manage clipboard and fix all pasted blocks (in fact, all blocks but others must have already been fixed)
		if ( contentPasted ) {
			fixAll()
			return
		}

		const currentBlockId = getSelectedBlockClientId()
		if ( null === currentBlockId ) return

		// Fixes the typography of current selected block
		theRegs && fixIt( { currentBlockId, theRegs } )
		
	} )
} )
